### ISSUE TITLE
how did you make planet/height textre

### ISSUE THREAD

**Issue by ghost** [Leopard501/PlanetMedley#3]
hi im jammer my discorse is ◢Jammer◣#4214 how did you make planeyt texture also why have no you join discord? anyways ydid you use gimp? this is not troll i need to know how you made planet/hieght textres

**Comment by Leopard501** [comment]
I am on the Discord, I'm just not very active on the modding server, I'm BlakeB#9894.

I used [Photopia](https://www.photopea.com/), and some of [these tutorials](https://forum.kerbalspaceprogram.com/index.php?/topic/165285-planetary-texturing-guide-repository/). Photopia is almost identical to Photoshop so Photoshop tutorials will work fine. I would not recommend using Gimp, I've used it in the past and I found it to be a total pain.

**Comment by Jammer232** [comment]
cool pog er but how to have rectangular to polar effect icant find it in
photopea even though i also use it i will sue

**Comment by Leopard501** [comment]
Pretty sure this was answered in the discord, but filter>distort>polar coordinates

**Comment by Jammer232** [comment]
why gmail no delete messages will sye for not deleteing
